In [33]:
import numpy as np
def sylvester_matrix(coeff1, coeff2):
    A = np.zeros((len(coeff1)+len(coeff2)-2, len(coeff1)+len(coeff2)-2))
    for i in range(len(coeff2)-1):
        A[i,i:len(coeff1)+i] = coeff1
    for i in range(len(coeff1)-1):
        A[i+len(coeff2)-1,i:i+len(coeff2)] = coeff2
    return A

In [34]:
coeff_p  = [1, -3, 1, -3]
coeff_q = [1, 1, -12]

print(sylvester_matrix(coeff_p, coeff_q))

[[  1.  -3.   1.  -3.   0.]
 [  0.   1.  -3.   1.  -3.]
 [  1.   1. -12.   0.   0.]
 [  0.   1.   1. -12.   0.]
 [  0.   0.   1.   1. -12.]]


In [35]:
syl_mat = sylvester_matrix(coeff_p, coeff_q)

numerator = np.delete(np.delete(syl_mat, 0, axis=1), -1, axis=0)
denominator = np.delete(np.delete(syl_mat, 1, axis=1), -1, axis=0)

common_root = -1 * np.linalg.det(numerator)/np.linalg.det(denominator)
# print common_root to 3 decimal places float
print("{:.3f}".format(common_root))

3.000
