## Question 3.b

In [27]:
import numpy as np

# Define the matrix
A_3 = np.array([[1, 1, 1],
                [10, 2, 9],
                [8, 0, 7]])

# Perform Singular Value Decomposition (SVD)
U, S, VT = np.linalg.svd(A_3)

# Define the vector b
b = np.array([[1], [3], [1]])

In [28]:
S

array([1.72832333e+01, 1.51322343e+00, 1.63228421e-15])

In [29]:
x_ = VT.T @ np.linalg.pinv(np.diag(S)) @ U.T @ b

In [30]:
x_

array([[0.01754386],
       [0.85964912],
       [0.12280702]])

In [32]:
VT.T[:, 2]

array([ 0.65561007,  0.09365858, -0.74926865])

## Question 3.c

In [35]:
import numpy as np
A = np.array([[ 1, 1, 1],
              [ 10, 2, 9],
              [ 8, 0, 7]])
U, S, VT = np.linalg.svd(A)
b=np.array([[3],[2],[2]])
x_ = VT.T @ np.linalg.pinv(np.diag(S)) @ U.T @ b

In [34]:
x_

array([[0.01754386],
       [0.85964912],
       [0.12280702]])