## Question 2.1

In [1]:
import numpy as np

A_1 = np.array([[ 10, 10, 1],
                [ 0, -4, 2],
                [ 2, 0, -4]])

U, S, VT = np.linalg.svd(A_1)

In [2]:
U 

array([[-0.97586837, -0.17298018,  0.13326206],
       [ 0.19874941, -0.45086605,  0.87018301],
       [-0.09044108,  0.87566983,  0.47436563]])

In [3]:
S

array([14.49903717,  4.57803496,  3.13361088])

In [4]:
VT

array([[-0.68553282, -0.72788843, -0.01493928],
       [ 0.00470461,  0.0160904 , -0.99985947],
       [ 0.72802652, -0.68550677, -0.00760607]])

## Question 2.2

In [5]:
import numpy as np

A_2 = np.array([[ 5, -5, 0, 0],
                    [ 5,  5, 5, 0],
                    [ 0, -1, 4, 1],
                    [ 0,  4, -1, 2],
                    [ 0,  0, 2, 1]])

U, S, VT = np.linalg.svd(A_2)

In [6]:
U

array([[ 0.1126266 ,  0.86708016,  0.37480574, -0.30750061, -0.0212435 ],
       [-0.93215705,  0.15225202,  0.1626033 ,  0.2846251 ,  0.0212435 ],
       [-0.20196646,  0.2257811 , -0.74973268, -0.31691184, -0.4956816 ],
       [-0.2398716 , -0.41225956,  0.38334628, -0.77085017, -0.17702914],
       [-0.14166742,  0.06368894, -0.35217519, -0.36026217,  0.84973988]])

In [7]:
S

array([9.14492811, 7.79814769, 4.42070712, 2.23976139])

In [8]:
VT

array([[-0.44807922, -0.65407164, -0.60275097, -0.09003647],
       [ 0.65357327, -0.69875055,  0.28263403, -0.06861233],
       [ 0.60783153,  0.27645026, -0.74051747, -0.07582844],
       [-0.05106685,  0.08667875,  0.09188657, -0.99067443]])

## Question 2.3

In [9]:
import numpy as np

A_3 = np.array([[ 1, 1, 1],
                [ 10, 2, 9],
                [ 8, 0, 7]])

U, S, VT = np.linalg.svd(A_3)

In [10]:
U

array([[-0.08686637, -0.57077804, -0.81649658],
       [-0.78592384, -0.4643889 ,  0.40824829],
       [-0.6121911 ,  0.67716718, -0.40824829]])

In [11]:
S

array([1.72832333e+01, 1.51322343e+00, 1.63228421e-15])

In [12]:
VT

array([[-0.74312678, -0.09597244, -0.66223249],
       [ 0.1339329 , -0.99096789, -0.0066797 ],
       [ 0.65561007,  0.09365858, -0.74926865]])