## Question 3.b

In [1]:
import numpy as np

# Define the matrix
A_3 = np.array([[1, 1, 1],
                [10, 2, 9],
                [8, 0, 7]])

# Perform Singular Value Decomposition (SVD)
U, S, VT = np.linalg.svd(A_3)

# Define the vector b
b = np.array([1, 3, 1])

In [2]:
S

array([1.72832333e+01, 1.51322343e+00, 1.63228421e-15])

In [3]:
x_= VT.T @ np.linalg.inv(np.diag(S)) @ U.T @ b

In [4]:
x_

array([-0.1875   ,  0.8359375,  0.3125   ])

In [5]:
VT.T[:2]

array([[-0.74312678,  0.1339329 ,  0.65561007],
       [-0.09597244, -0.99096789,  0.09365858]])

## Question 3.c

In [6]:
import numpy as np
A = np.array([[ 1, 1, 1],
              [ 10, 2, 9],
              [ 8, 0, 7]])
U, S, VT = np.linalg.svd(A)
b=np.array([3,2,2])
x_= VT.T @ np.linalg.inv(np.diag(S)) @ U.T @ b

In [7]:
x_

array([-9.83842227e+14, -1.40548890e+14,  1.12439112e+15])