In [ ]:
import numpy as np
import copy

In [ ]:
list(range(2,5))

In [ ]:
def LowerTriangularization(dim):
        for i in range(dim):
            Li = np.zeros((dim, dim))
            for j in range(i+1, dim):
                print(i,j)

LowerTriangularization(3)

In [ ]:
import numpy as np

def lower_triangularization(A):
    dim = A.shape[0]
    L = []
    for i in range(dim):
        for j in range(i + 1, dim):
            Li = np.eye(dim)
            Li[j, i] = A[j, i] / A[i, i]
            A[j, :] = A[j, :] - (A[j, i] / A[i, i]) * A[i, :]
            L.append(Li)
            print(Li)
    
    return L, A

In [185]:
import numpy as np
import copy

class GaussianElimination:
    """
    A class to perform Gaussian Elimination on a given matrix A, decomposing it into
    permutation (P), lower triangular (L), diagonal (D), and upper triangular (U) matrices.
    """

    def __init__(self, A):
        """
        Initialize the GaussianElimination class with matrix A.

        Parameters:
        -----------
        A : np.ndarray
            The matrix to be decomposed.
        """
        self.A = A.astype(np.float64)  # Ensure matrix A is of dtype np.float64
        self.A_ = copy.deepcopy(self.A)  # Create a deep copy of A to avoid modifying the original matrix
        self.initialize_matrices()

    def initialize_matrices(self):
        """
        Initialize matrices P, L, D, and U based on the dimension of matrix A.
        """
        self.dim = self.A.shape[0]

        # Initialize permutation matrix P as an identity matrix
        self.P = np.eye(self.dim, dtype=np.float64)
        
        # Initialize L as a zero matrix and U, D as zero matrices
        self.L = np.zeros((self.dim, self.dim), dtype=np.float64)
        self.D = np.zeros((self.dim, self.dim), dtype=np.float64)
        self.U = np.zeros((self.dim, self.dim), dtype=np.float64)

    def first_non_zero_index(self, idx):
        """
        Find the index of the first non-zero element in the sub-array starting from index `idx`.

        Parameters:
        -----------
        idx : int
            The starting index for the search in the sub-array.

        Returns:
        --------
        int
            The index of the first non-zero element in the sub-array.
        """
        column = self.A_[idx:, idx]
        non_zero_indices = np.nonzero(column)[0]

        return non_zero_indices[0] + idx

    def permutation_matrix_colswap(self, col1, col2):
        """
        Swap two columns in the permutation matrix P.

        Parameters:
        -----------
        col1 : int
            The first column to swap.
        col2 : int
            The second column to swap.
        """
        self.P[:, [col1, col2]] = self.P[:, [col2, col1]]

    def swap_rows(self, matrix, row1, row2):
        """
        Swap two rows in a given matrix.

        Parameters:
        -----------
        matrix : np.ndarray
            The matrix in which rows will be swapped.
        row1 : int
            The first row to swap.
        row2 : int
            The second row to swap.

        Returns:
        --------
        np.ndarray
            The matrix with the specified rows swapped.
        """
        matrix[[row1, row2], :] = matrix[[row2, row1], :]
        return matrix

    def lower_triangularization(self):
        """
        Perform lower triangularization of matrix A.

        This method transforms matrix A into a lower triangular form by applying
        a series of row operations, and updates matrix L accordingly.
        """
        for i in range(self.dim):
            # Handle zero pivot by row swapping
            if self.A_[i, i] == 0:
                interchange_idx = self.first_non_zero_index(i)
                self.permutation_matrix_colswap(i, interchange_idx)  # Swap columns in permutation matrix
                self.A_ = self.swap_rows(self.A_, i, interchange_idx)  # Swap rows in A_
                self.L = self.swap_rows(self.L, i, interchange_idx)  # Swap rows in L

            # Perform row operations to create zeros below the pivot
            for j in range(i + 1, self.dim):
                multiplier = self.A_[j, i] / self.A_[i, i]
                self.L[j, i] = multiplier
                self.A_[j, :] -= multiplier * self.A_[i, :]

        # Add identity matrix to L to finalize lower triangular form
        self.L += np.eye(self.dim)

    def extract_diagonal_and_upper(self):
        """
        Extract the diagonal (D) and upper triangular (U) matrices from A_.
        """
        for i in range(self.dim):
            self.D[i, i] = self.A_[i, i]  # Extract diagonal elements
            self.U[i, :] = self.A_[i, :]  # Extract upper triangular part

        # Normalize U to ensure ones on the diagonal
        for i in range(self.dim):
            if self.D[i, i] != 0:
                self.U[i, :] /= self.D[i, i]

    def decompose(self):
        """
        Perform Gaussian Elimination to decompose matrix A into L, D, U, and P.

        Returns:
        --------
        tuple of np.ndarray
            A tuple containing the lower triangular matrix (L),
            diagonal matrix (D), upper triangular matrix (U), and permutation matrix (P).
        """
        self.lower_triangularization()
        self.extract_diagonal_and_upper()
        return self.L, self.D, self.U, self.P

In [186]:
A = np.array([[1,3,2], [-2,-6,1], [2,5,7]], dtype=np.float64)

GE = GaussianElimination(A)
L,D,U,P = GE.decompose()

In [187]:
L

array([[ 1.,  0.,  0.],
       [ 2.,  1.,  0.],
       [-2.,  0.,  1.]])

In [188]:
D

array([[ 1.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 0.,  0.,  5.]])

In [181]:
U

array([[ 1.,  3.,  2.],
       [-0.,  1., -3.],
       [ 0.,  0.,  1.]])

In [184]:
P

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])